name: Deploy to Firebase

on:
  pull_request:
    types:
      - closed
  branches:
    - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm install  # 또는 yarn install

      - name: 프로젝트 빌드
        run: npm run build  # React는 npm run build, Vue는 npm run build --prod

      - name: Firebase CLI 설치
        run: npm install -g firebase-tools

      - name: Firebase 배포
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
